#!/bin/sh

set -e

USER="gorcon"
GROUP="gorcon"
SERVICE="gorcon-arma.service"

case "$1" in
	remove)
	;;

	purge)
		set +e

		update-rc.d ${SERVICE} remove >/dev/null

		deluser ${USER}
		delgroup ${GROUP}

		set -e
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "$0 called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

exit 0
